theme: jekyll-theme-cayman
title: BlueBubbles
description: Use iMessage seemlessly on your Android device!
show_downloads: true
google_analytics: UA-168573615-1
github:
  server_release_url: https://github.com/BlueBubblesApp/BlueBubbles-Server/releases
  source_code_url: https://github.com/BlueBubblesApp
  android_release_url: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/releases
pages:
  next_page: /guide
  next_page_title: Installation Guide