theme: jekyll-theme-cayman
title: BlueBubbles | Installation Guide
description: How you can install BlueBubbles
show_downloads: false
google_analytics: UA-168573615-1
pages:
  next_page: /
  next_page_title: Home